[build]
command = "npm run build"
publish = "dist"

[[redirects]]
  from = "https://classic-mapbox-styles.dataviz.jp/*"
  to = "https://classic-mapbox-styles.dataprep.jp/:splat"
  status = 301
  force = true
